### ISSUE TITLE
Additional Language Support

### ISSUE THREAD

**Issue by zmohammad01** [ko31/simple-slug-translate#25]
@ko31 Hello

I am the product manager for Watson Language Translator. I wanted to reach out to ask if you are able to update your app to reflect the most up to date list of languages that are supported by our service. It's far great than the 9 which are publically listed on the GH repo and on the plugin. 

```
Arabic, Catalan, Chinese (Simplified & Traditional), Czech, Danish, Dutch, English, Finnish, French, German, Hindi, Hungarian, Italian, Japanese, Korean, Norwegian, Polish, Portuguese (Brazil), Russian, Spanish, Swedish, and Turkish
```

Additionally, we have support for document translation (MS Office, Open Office, PDF, HTML, JSON, TXT & and XML), perhaps that might be a feature enhancement to add to your plugins value prop?

Cheers
Zia

**Comment by ko31** [comment]
@zmohammad01 

Awesome! 
I did not know the information, so I would like to try it. 👍

**Comment by ko31** [comment]
Done.
