### ISSUE TITLE
Getting Invalid Settings Error with 400 Error Code

### ISSUE THREAD

**Issue by sshobhi776** [ko31/simple-slug-translate#37]
Hi,

I have added my API keys but the plugin is showing an Invalid Setting with 400 error code.
Could you please fix it?

Please see screenshot- https://prnt.sc/x6ap7b

Thank you.

**Comment by ko31** [comment]
@sshobhi776 

I replied to support below. How about it?
https://wordpress.org/support/topic/plugin-is-not-working-400-error/

**Comment by ko31** [comment]
I'm closing this issue.
